language: php
dist: trusty
sudo: false

php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.drush/cache

install:
  - composer install --no-interaction
  - composer global require 'drush/drush:^8.0'

env:
  - PLATFORMSH_CLI_DRUSH=$HOME/.composer/vendor/bin/drush

script:
  - 'curl -H "Accept: text/plain" https://security.sensiolabs.org/check_lock -F lock=@./composer.lock'
  - ./vendor/bin/phpunit -c ./phpunit.xml --coverage-text --exclude-group slow
